### ISSUE TITLE
Example to generate 1000 BTC and ETH addresses

### ISSUE THREAD

**Issue by senzacionale** [ranaroussi/pywallet#1]
Hi,

thank you for this nice code. But I would like to see example how to generate 1000 BTC addresses and 1000 ETH addresses with private and public key.

```
Create Child Wallet

You can create child-wallets (BIP32 wallets) from the HD wallet's Extended Public Key to generate new public addresses without revealing your private key.
```

What is here a private key?
`
WALLET_PUBKEY = 'YOUR WALLET XPUB'`

Where can I get xpub? Is this xprivate_key

Thank you

**Comment by ranaroussi** [comment]
When you create a new wallet, you'll find ``xpublic_key`` as one of the keys. If you want to use your existing wallet's ``xpub``, you'll need to follow the instructions on your wallet software or service ([blockchain.info example](https://support.blockchain.com/hc/en-us/articles/207746403-Addresses))
