### ISSUE TITLE
all ETH network childs has the same address

### ISSUE THREAD

**Issue by cscsabai** [ranaroussi/pywallet#26]
I'm trying to generate many addresses for Ethereum with HDwallet seed, but all generated address is the same. Am I do something wrong?

**Comment by cscsabai** [comment]
The problem probably is in wallet.py create_address() function. After declare the keys (HDKey.from_path) use the -1 index for bip32_path for the 1 index for the address. It can generate valid keys after I modify the indexes exactly to "-1"

But I have to check it...

**Comment by ranaroussi** [comment]
Fixed in 0.1.0
