### ISSUE TITLE
omni network Prefix and coin type bug

### ISSUE THREAD

**Issue by zhoudaqing** [ranaroussi/pywallet#28]
omni network Prefix bug
https://github.com/ranaroussi/pywallet/blob/master/pywallet/network.py   54 and  55
https://github.com/ranaroussi/pywallet/blob/206ff224389c490d8798f660c9e79fe97ebb64cf/pywallet/network.py#L54
![image](https://user-images.githubusercontent.com/345925/45266796-66a3c080-b493-11e8-80f3-2efc1226992a.png)

omnicore source code
https://github.com/OmniLayer/omnicore/blob/develop/src/chainparams.cpp   128 and 129
https://github.com/OmniLayer/omnicore/blob/c0738a96b587c80a73f93cb653c032e1cc95b6f4/src/chainparams.cpp#L128
![image](https://user-images.githubusercontent.com/345925/45266812-bb473b80-b493-11e8-8b80-75b15c8d949b.png)

SLIP-0044 : Registered coin types for BIP-0044
Omni Coin type is “200” ，omni BIP32_PATH： "m/44'/200'/..."
https://github.com/satoshilabs/slips/blob/master/slip-0044.md

**Comment by zhoudaqing** [comment]
@ranaroussi  We have sent the USDT to the wrong omni address. Is there a solution?

**Comment by ranaroussi** [comment]
Unfortunately, once you send funds to a blockchain address, there's no way to get it out unless you have the private keys to that address...
