### ISSUE TITLE
Xpub header is Ltub for Litecoin but perhaps should be the same as BTC

### ISSUE THREAD

**Issue by jrestifo** [ranaroussi/pywallet#6]
I tried to use my xpub from Electrum to generate a watching only wallet, but it failed. After digging around I realized Electrum was using xpub, not Ltub. I found that strange, and thought it was a mistake in Electrum but it seems that it is actually pywallet that isn't following conventions, according to this LTC dev:
[Response from LTC dev](https://www.reddit.com/r/litecoin/comments/7rorqa/electrum_using_bitcoin_xpub_headers/dszq9d5/?context=3)

**Comment by ranaroussi** [comment]
Fixed
